// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections;
using System.Collections.Generic;

namespace FluxoDeCaixa.Domain.Entity;

public partial class TipoLancamento
{
    public TipoLancamento()
    {
        Lancamento = new List<Lancamento>();
        Descricao = string.Empty;
    }
    public int TipoLancamentoId { get; set; }

    public string Descricao { get; set; }

    public virtual IList<Lancamento> Lancamento { get; set; } 
}