// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ReverseEF.Models;

public partial class Lancamento
{
    public int LancamentoId { get; set; }

    public DateTime Data { get; set; }

    public decimal Valor { get; set; }

    public int TipoLancamentoId { get; set; }

    public string Descricao { get; set; }

    public bool Estornado { get; set; }

    public string Observacao { get; set; }

    public virtual TipoLancamento TipoLancamento { get; set; }
}