// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ReverseEF.Models;

public partial class TipoLancamento
{
    public int TipoLancamentoId { get; set; }

    public string Descricao { get; set; }

    public virtual ICollection<Lancamento> Lancamento { get; } = new List<Lancamento>();
}