// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FluxoDeCaixa.Domain.Entity;

public partial class LancamentoViewModel
{
    public LancamentoViewModel()
    {
        Descricao = string.Empty;
        Observacao = string.Empty;
    }

    public int LancamentoId { get; set; }

    public DateTime Data { get; set; }

    public decimal Valor { get; set; }

    public int TipoLancamentoId { get; set; }

    public string Descricao { get; set; }

    public string Observacao { get; set; }

    public virtual TipoLancamentoViewModel TipoLancamento { get; set; }
}