// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections;
using System.Collections.Generic;

namespace FluxoDeCaixa.Domain.Entity;

public partial class TipoLancamentoViewModel
{
    public TipoLancamentoViewModel()
    {
        Lancamento = new List<LancamentoViewModel>();
        Descricao = string.Empty;
    }
    public int TipoLancamentoId { get; set; }

    public string Descricao { get; set; }

    public virtual IList<LancamentoViewModel> Lancamento { get; set; } 
}