USE [master]
GO

/****** Object:  Database [FluxoCaixa]    Script Date: 16/05/2023 11:14:51 ******/
CREATE DATABASE [FluxoCaixa]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FluxoCaixa', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.DEV\MSSQL\DATA\FluxoCaixa.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'FluxoCaixa_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.DEV\MSSQL\DATA\FluxoCaixa_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FluxoCaixa].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [FluxoCaixa] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [FluxoCaixa] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [FluxoCaixa] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [FluxoCaixa] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [FluxoCaixa] SET ARITHABORT OFF 
GO

ALTER DATABASE [FluxoCaixa] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [FluxoCaixa] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [FluxoCaixa] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [FluxoCaixa] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [FluxoCaixa] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [FluxoCaixa] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [FluxoCaixa] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [FluxoCaixa] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [FluxoCaixa] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [FluxoCaixa] SET  DISABLE_BROKER 
GO

ALTER DATABASE [FluxoCaixa] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [FluxoCaixa] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [FluxoCaixa] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [FluxoCaixa] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [FluxoCaixa] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [FluxoCaixa] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [FluxoCaixa] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [FluxoCaixa] SET RECOVERY FULL 
GO

ALTER DATABASE [FluxoCaixa] SET  MULTI_USER 
GO

ALTER DATABASE [FluxoCaixa] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [FluxoCaixa] SET DB_CHAINING OFF 
GO

ALTER DATABASE [FluxoCaixa] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [FluxoCaixa] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [FluxoCaixa] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [FluxoCaixa] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [FluxoCaixa] SET QUERY_STORE = OFF
GO

ALTER DATABASE [FluxoCaixa] SET  READ_WRITE 
GO


